/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xujun;

/**
 *
 * @author Jun Xu
 */

class Node<T> {

    public T data;

    public Node(T data) { this.data = data; }

    public void setData(T data) {
        System.out.println("Node.setData");
        this.data = data;
    }
}

public class MyNode extends Node<Integer> {
    public MyNode(Integer data) { super(data); }

    public void setData(Integer data) {
        System.out.println("MyNode.setData");
        super.setData(data);
    }
    public static void main(String[] args){
        /*MyNode mn = new MyNode(5);
        Node n = mn;            // A raw type - compiler throws an unchecked warning
        n.setData("Hello");     
        Integer x = mn.data;    // Causes a ClassCastException to be thrown.*/
        MyNode mn = new MyNode(5);
        Node n = (MyNode)mn;         // A raw type - compiler throws an unchecked warning
        n.setData("Hello");
        Integer x = (Integer)mn.data; // Causes a ClassCastException to be thrown.
    }
}

//bridge methods
class NodeBridge {

    public Object data;

    public NodeBridge(Object data) { this.data = data; }

    public void setData(Object data) {
        System.out.println("Node.setData");
        this.data = data;
    }
}

class MyNodeBridge extends NodeBridge {
     // Bridge method generated by the compiler
    //
    public void setData(Object data) {
        setData((Integer) data);
    }//这就是Bridge method 是隐含的一个方法 本身是Object的类型强转成了String类型
//Bridge存在的原因：After type erasure, the method signatures do not match. The Node method becomes setData(Object) 
//and the MyNode method becomes setData(Integer). Therefore, the MyNode setData method does not override the Node setData method.

    public MyNodeBridge(Integer data) { super(data); }

    public void setData(Integer data) {
        System.out.println("MyNode.setData");
        super.setData(data);
    }
}
